dist: focal
services:
  - xvfb

language: java

jdk:
  - openjdk11

before_install:
  - wget "${COMPONENT_LINK}" -O $COMPONENT_NAME -q
  - echo "${DECRYPTER}" | gpg --pinentry-mode=loopback --passphrase-fd 0 $COMPONENT_NAME
  - eval "$IMPORT_COMPONENT"

install: true

script:
  - travis_retry mvn verify
  - travis_retry travis_wait mvn deploy --settings settings.xml

notifications:
  email:
    on_success: never

cache:
  directories:
  - $HOME/.m2
