dist: bionic
services:
  - xvfb

language: java

jdk:
  - openjdk11

before_install:
  - wget "${COMPONENT_LINK}" -O $COMPONENT_NAME -q
  - echo "${DECRYPTER}" | gpg --pinentry-mode=loopback --passphrase-fd 0 $COMPONENT_NAME
  - eval "$IMPORT_COMPONENT"

install: true

script:
  - mvn verify

notifications:
  email:
    on_success: never